### ISSUE TITLE
微信群二维码已过期哦

### ISSUE THREAD

**Issue by AuroraTea** [ppz-pro/ppz.vscode#23]

**Comment by daGaiGuanYu** [comment]
实在不好意思，github 的图片更新很慢……  
你可以试试 ![群](https://s1.328888.xyz/2022/07/29/DZN3F.png)  

或者点[这个链接](https://files20220620.oss-cn-shanghai.aliyuncs.com/ppz.vscode.jpg)，它会**下载**最新的群二维码图片。

**Comment by AuroraTea** [comment]
@daGaiGuanYu 好的好的，这没什么不好意思的吼吼
