### ISSUE TITLE
Insert suggestions for page changes

### ISSUE THREAD

**Issue by news-ttt** [ppz-pro/ppz.vscode#30]
Insert you want to insert it on the original display data list page, so that you can have a display comparison, and you can also copy the contents above to the new column

**Comment by news-ttt** [comment]
Just a suggestion

**Comment by daGaiGuanYu** [comment]
我没太看明白

**Comment by daGaiGuanYu** [comment]
我看得懂中文的

**Comment by news-ttt** [comment]
好的

**Comment by news-ttt** [comment]
好的

**Comment by news-ttt** [comment]
我这个就是提了个插入页面的修改建议：
+ 插入页面希望可以在显示列表页面存在，这样的话我插入时，可以有对比，以及复制的操作

**Comment by news-ttt** [comment]
只是一个建议，当然现在已经做的很好，而且看您是还有全职工作，很厉害

**Comment by daGaiGuanYu** [comment]
嗷嗷，谢谢，本来我也是这样打算的。  
不过这样有些问题：
##### 新插入的数据，显示在老数据们下方？还是上方？
这在页面尺寸较小的情况下，不成问题  
但是如果尺寸较大，在有滚动条的情况下，插入后的数据，很有可能出现在滚动条里面（用户看不到）

##### 在数据页面加入”插入“功能的话，页面功能太多
功能多本身不是一件坏事，但是一个小地方功能太多，就容易显得乱，而且不简洁

##### 建议
建议你试试”拷贝“按钮，你需要：
+ 先点击已存在的某条记录
+ 点击上部”拷贝“按钮
+ 被点击的数据将被发送到”插入数据“页面，你可以在这个基础上进行修改、保存，成功后会产生新纪录，而不是更新被拷贝的记录

**Comment by daGaiGuanYu** [comment]
> 只是一个建议，当然现在已经做的很好，而且看您是还有全职工作，很厉害

过奖了，公司都快让我们干黄了……

**Comment by news-ttt** [comment]
已经很厉害了，我上家公司也黄了

**Comment by news-ttt** [comment]
> 嗷嗷，谢谢，本来我也是这样打算的。 不过这样有些问题：
> 
> ##### 新插入的数据，显示在老数据们下方？还是上方？
> 这在页面尺寸较小的情况下，不成问题 但是如果尺寸较大，在有滚动条的情况下，插入后的数据，很有可能出现在滚动条里面（用户看不到）
> 
> ##### 在数据页面加入”插入“功能的话，页面功能太多
> 功能多本身不是一件坏事，但是一个小地方功能太多，就容易显得乱，而且不简洁
> 
> ##### 建议
> 建议你试试”拷贝“按钮，你需要：
> 
> * 先点击已存在的某条记录
> * 点击上部”拷贝“按钮
> * 被点击的数据将被发送到”插入数据“页面，你可以在这个基础上进行修改、保存，成功后会产生新纪录，而不是更新被拷贝的记录

好的谢谢

**Comment by daGaiGuanYu** [comment]
> 已经很厉害了，我上家公司也黄了

我们真是反资本家的斗士！
