### ISSUE TITLE
关于固定翻页条的问题

### ISSUE THREAD

**Issue by xushuhui** [ppz-pro/ppz.vscode#31]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/13704743/182549325-ac19be1e-282d-4bfd-a818-21b878466c4e.png">
当我拉到最底下的时候想翻页，必须又滑上去点击下一页，操作不方便，能否上下滑动的时候固定这一栏。

**Comment by daGaiGuanYu** [comment]
页面尺寸别设置太大
