### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by changzhenlin** [ppz-pro/ppz.vscode#32]
there is no results to show after add filters

**Comment by daGaiGuanYu** [comment]
我不太确定:
+ 你的表里有没有数据
+ 你的搜索条件正不正确
+ 你的搜索条件能不能搜到数据

我很想帮你解决问题  
但是你得告诉我你是什么问题  
你不能不给我试卷, 就问我第 7 题怎么做  

PS 我看得懂中文的
