### ISSUE TITLE
BUG: sqlite创建连接时，弹出窗口不能正常关闭

### ISSUE THREAD

**Issue by orangelckc** [ppz-pro/ppz.vscode#34]
系统：MacOS 12.4
插件版本：v0.3.1
复现步骤：创建连接->选择sqlite3->双击filename，此时会有弹出窗口
BUG：
1. 如果不选择文件，窗口不能关闭，点击取消后会再次自动弹出
2. 选择文件后，窗口也会消失后自动又弹出
3. feat: 此处应该对文件类型进行筛选，不应该开放所有类型的选择

**Comment by daGaiGuanYu** [comment]
非常抱歉，PPZ 目前对 mac 上的 sqlite3 还未正式支持  
不过，现在不兼容的问题已经解决得差不多了  
你可以通过 [这些步骤](https://github.com/ppz-pro/ppz.vscode/wiki/%E6%94%AF%E6%8C%81-macOS-%E4%B8%8A%E7%9A%84-sqlite3) 在自己电脑上打个 PPZ 的包  
如果有问题的话，可以随时反馈到这里，我一定会尽快帮你解决  
或者你也可以[加入 PPZ 的微信群聊](https://github.com/ppz-pro/ppz.vscode/issues/23)，那里的反馈更加及时

另外，“对文件类型的筛选”  
我也非常想进行筛选，不过除了对文件后缀名进行读取之外，我不清楚有其他什么办法（来区分文件类型）  
但是，sqlite3 又没有一个固定的后缀名，它甚至不必需要一个后缀名  
甚至，png 的后缀名也是理论上可能存在的

**Comment by orangelckc** [comment]
> 非常抱歉，PPZ 目前对 mac 上的 sqlite3 还未正式支持 不过，现在不兼容的问题已经解决得差不多了 你可以通过 [这些步骤](https://github.com/ppz-pro/ppz.vscode/wiki/%E6%94%AF%E6%8C%81-macOS-%E4%B8%8A%E7%9A%84-sqlite3) 在自己电脑上打个 PPZ 的包 如果有问题的话，可以随时反馈到这里，我一定会尽快帮你解决 或者你也可以[加入 PPZ 的微信群聊](https://github.com/ppz-pro/ppz.vscode/issues/23)，那里的反馈更加及时
> 
> 另外，“对文件类型的筛选” 我也非常想进行筛选，不过除了对文件后缀名进行读取之外，我不清楚有其他什么办法（来区分文件类型） 但是，sqlite3 又没有一个固定的后缀名，它甚至不必需要一个后缀名 甚至，png 的后缀名也是理论上可能存在的

感谢回复，抱歉没注意到sqlite不支持mac的提示，顺便期待一下下个版本能解决现在的问题！

**Comment by daGaiGuanYu** [comment]
[哭][哭][哭]，最近在[找工作，非常忙](https://dagaiguanyu.github.io/Resume/dist/)，你可能要多等一阵了……  
不过我试了 [这个步骤](https://github.com/ppz-pro/ppz.vscode/wiki/%E6%94%AF%E6%8C%81-macOS-%E4%B8%8A%E7%9A%84-sqlite3) 真的可以用的

**Comment by daGaiGuanYu** [comment]
这个问题应该是解决了，刚刚发布了最新版本

**Comment by daGaiGuanYu** [comment]
我试了几次，应该没问题了，目前先关闭这个问题
感谢使用 皮皮仔，如果你觉得好用请帮忙做做宣传~
