### ISSUE TITLE
ssl 

### ISSUE THREAD

**Issue by karl19** [ppz-pro/ppz.vscode#35]
老板，能不能增加一个ssl的选项？
谢谢。

**Comment by daGaiGuanYu** [comment]
mysql 吗，可以参考一下 [mysql 的驱动](http://172.20.100.123/BDS8820Q312/bitinvo-equipment/wikis/%E4%B8%9A%E5%8A%A1)  
Pgsql 可以参考[这个](https://node-postgres.com/features/connecting#connection-uri)  

因为建立连接时，可提供的属性特别特别多，所以目前只提供了最常用的字段  
**其他字段可以使用 url 进行连接**
