### ISSUE TITLE
有没有大佬打包遇到这种

### ISSUE THREAD

**Issue by pit-heqiang** [ppz-pro/ppz.vscode#37]
![99f05dc7f6c49c62331608e0757f0af](https://user-images.githubusercontent.com/23444743/187616175-f1ff4af6-bd15-4774-8aed-63893c60c41e.png)

**Comment by pit-heqiang** [comment]
![3144ec605106b1f6c6124745283849c](https://user-images.githubusercontent.com/23444743/187616321-94269f70-c6ed-48cc-95d5-55509ffba04f.jpg)
贴错了

**Comment by daGaiGuanYu** [comment]
应该是已经解决了吧，关闭了哦
